### ISSUE TITLE
static versus php 5.2

### ISSUE THREAD

**Issue by TinekeinTOWN** [stephenh1988/Radio-Buttons-for-Taxonomies#2]
This code :
        `public static function remove_meta_box(){  
        remove_meta_box(static::$taxonomy_metabox_id, static::$post_type, 'normal');  
     } 
        public function add_meta_box() {  
        add_meta_box( 'mytaxonomy_id', 'Formats',array(__CLASS__,'metabox'), static::$post_type ,'side','core');  
    }`

Is giving me this error on my live server:
`Parse error: syntax error, unexpected T_STATIC, expecting ')'`

Which probably has to do with the fact my server is still running PHP 5.2.17 ?
Since I can't upgrade the PHP version: is there any other option to make this work?

**Comment by stephenh1988** [comment]
Yeah it seems this won't work before 5.3. Does changing `static::$variable` to `self::$variable` work?

**Comment by TinekeinTOWN** [comment]
Gonna check that one out right now... back in a sec

**Comment by TinekeinTOWN** [comment]
It does! Thank you so much!
